### ISSUE TITLE
api/projects/${projectId}/applications returns duplicate data

### ISSUE THREAD

**Issue by hustLer2k** [artsiomshshshsk/teamder#7]
https://teamder-dev.herokuapp.com/api/projects/${projectId}/applications returns 7 objects for 1 application

![image](https://user-images.githubusercontent.com/61846786/226921447-4ab272dc-f0fb-4c15-9d30-a2a7db591a69.png)

@artsiomshshshsk

**Comment by hustLer2k** [comment]
resumeURLs are null btw
![image](https://user-images.githubusercontent.com/61846786/226932473-5b342414-7cfe-49d9-9687-5b534177d9a3.png)

**Comment by artsiomshshshsk** [comment]
@hustLer2k both of them are fixed now
